"""Resolve and hash-lock dependencies for the supported production runtime."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from urllib.parse import quote
from urllib.request import Request, urlopen


TARGET_ARGUMENTS = (
    "--only-binary=:all:",
    "--platform",
    "manylinux_2_17_x86_64",
    "--implementation",
    "cp",
    "--abi",
    "cp312",
    "--python-version",
    "3.12",
)


def canonical_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def resolve_dependencies(source: Path) -> list[dict[str, object]]:
    """Ask pip to resolve packages without modifying the local environment."""
    with tempfile.TemporaryDirectory() as temporary_directory:
        report_path = Path(temporary_directory) / "pip-report.json"
        command = [
            sys.executable,
            "-m",
            "pip",
            "install",
            "--dry-run",
            "--ignore-installed",
            "--report",
            str(report_path),
            *TARGET_ARGUMENTS,
            "-r",
            str(source),
        ]
        subprocess.run(command, check=True)
        report = json.loads(report_path.read_text(encoding="utf-8"))
    installs = report.get("install")
    if not isinstance(installs, list):
        raise RuntimeError("pip did not produce a dependency installation report.")
    return installs


def release_hashes(name: str, version: str) -> list[str]:
    """Returns every published SHA-256 for the selected PyPI release."""
    url = f"https://pypi.org/pypi/{quote(name)}/{quote(version)}/json"
    request = Request(url, headers={"User-Agent": "institutional-reasoning-engine-locker"})
    with urlopen(request, timeout=30) as response:  # nosec B310: fixed PyPI API URL
        payload = json.loads(response.read().decode("utf-8"))
    urls = payload.get("urls")
    if not isinstance(urls, list):
        raise RuntimeError(f"PyPI returned no release files for {name}=={version}.")
    hashes = sorted(
        {
            file_info.get("digests", {}).get("sha256")
            for file_info in urls
            if isinstance(file_info, dict)
            and isinstance(file_info.get("digests", {}).get("sha256"), str)
        }
    )
    if not hashes:
        raise RuntimeError(f"PyPI returned no SHA-256 hashes for {name}=={version}.")
    return hashes


def render_lock(installs: list[dict[str, object]]) -> str:
    packages: list[tuple[str, str]] = []
    for item in installs:
        metadata = item.get("metadata") if isinstance(item, dict) else None
        if not isinstance(metadata, dict):
            raise RuntimeError("pip report contains an installation without package metadata.")
        name = metadata.get("name")
        version = metadata.get("version")
        if not isinstance(name, str) or not isinstance(version, str):
            raise RuntimeError("pip report contains an installation without a name and version.")
        packages.append((canonical_name(name), version))

    lines = [
        "# Generated by tools/lock_python_dependencies.py. DO NOT EDIT.",
        "# Source: requirements.in. Target: CPython 3.12 on Linux (manylinux_2_17_x86_64).",
        "# Refresh with: python tools/lock_python_dependencies.py",
        "--only-binary=:all:",
        "",
    ]
    for name, version in sorted(packages):
        hashes = release_hashes(name, version)
        lines.append(f"{name}=={version} \\")
        for index, digest in enumerate(hashes):
            continuation = " \\" if index < len(hashes) - 1 else ""
            lines.append(f"    --hash=sha256:{digest}{continuation}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=Path("requirements.in"))
    parser.add_argument("--output", type=Path, default=Path("requirements.txt"))
    arguments = parser.parse_args()
    arguments.output.write_text(render_lock(resolve_dependencies(arguments.source)), encoding="utf-8")


if __name__ == "__main__":
    main()
